import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Pixel Image",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // From #E3D1FB then  #FDD2E4 then #FFDEE1 then #FFFCF8 then #FFFFFF
        className={cn(
          "min-h-screen bg-background font-mono antialiased",
          fontSans.variable
        )}
        style={{
          // Inline style for the gradient
          background:
            "linear-gradient(30deg, #E3D1FB, #E3D1FB, #E3D1FB, #FDD2E4, #FFDEE1, #FFFCF8, #FFFFFF)",
        }}
      >
        {children}
      </body>
    </html>
  );
}
