import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Analytics } from "@vercel/analytics/react";
import Header from "@/components/Header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Pixel Image",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics />
      <body
        className={cn(
          "min-h-screen bg-background font-mono antialiased",
          fontSans.variable
        )}
        style={{
          background:
            "linear-gradient(30deg, #E3D1FB, #E3D1FB, #E3D1FB, #FDD2E4, #FFDEE1, #FFFCF8, #FFFFFF)",
        }}
      >
        <Header />
        <main className="flex min-h-screen flex-col items-center justify-start lg:p-24 ">
          {children}
        </main>
      </body>
    </html>
  );
}
